-- -- disable netrw
-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- -- optionally enable 24-bit colour
-- vim.opt.termguicolors = true
--
-- -- setup with some options
-- local nvim_tree = require("nvim-tree")
--
-- nvim_tree.setup({
--   sort = { sorter = "case_sensitive" },
--   view = { width = 30 },
--   renderer = { group_empty = true },
--   filters = { dotfiles = true },
--
--   -- auto-open in all tabs
--   open_on_tab = true,
--   hijack_cursor = true,
--   update_focused_file = { enable = true, update_cwd = true },
--
--   on_attach = function(bufnr)
--     local api = require("nvim-tree.api")
--     api.config.mappings.default_on_attach(bufnr)
--
--     local function opts(desc)
--       return { buffer = bufnr, noremap = true, silent = true, nowait = true, desc = desc }
--     end
--
--     -- Open folder in parent
--     vim.keymap.set("n", "<C-t>", api.tree.change_root_to_parent, opts("Up"))
--     vim.keymap.set("n", "?", api.tree.toggle_help, opts("Help"))
--
--     -- Open first file in current window, then subsequent files in tab
--     vim.keymap.set("n", "<CR>", function()
--       local node = api.tree.get_node_under_cursor()
--       if node.nodes then
--         api.node.open.edit() -- folder
--       else
--         -- open file in current window the first time
--         api.node.open.edit()
--         -- override <CR> to open in tab next time
--         vim.keymap.set("n", "<CR>", function()
--           local node2 = api.tree.get_node_under_cursor()
--           if node2.nodes then
--             api.node.open.edit()
--           else
--             api.node.open.tab()
--           end
--         end, { buffer = bufnr, desc = "Open file in tab" })
--       end
--     end, opts("Open file or folder"))
-- 	-- TAB navigation inside nvim-tree buffer
--   	vim.keymap.set("n", "<Tab>", "gt", opts("Next tab"))
--   	vim.keymap.set("n", "<S-Tab>", "gT", opts("Previous tab"))
--   end,
-- })
